[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "soundsig"
description = "Sound and Signal Analysis Tools for Bioacousticians and Auditory Neurophysiologists"
version = "2.1"
authors = [{name = "frederic Theunissen", email = "theunissen@berkeley.edu"}]
readme = "README.md"
license = {file = "LICENSE"}
keywords = ['bioacoustics' ,'biosound', 'vocalization', 'auditory']
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.0"
]
requires-python = ">=3.10, <3.12"
dependencies = [
    'numpy>=2.0.2',
    'scipy>=1.14.1',
    'matplotlib>=3.9.2',
    'h5py>=3.12.1',
    'librosa>=0.10.2.post1',
    'mne>=1.8.0',
    'nitime>=0.11',
    'numba>=0.60.0',
    'pandas>=2.2.3',
    'scikit-learn>=1.5.2',
]

[project.urls]
Home = "https://github.com/theunissenlab/soundsig"

[project.optional-dependencies]
generate-test-data = ["jupyterlab", "xarray"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
soundsig = { path = ".", editable = true }

[tool.pixi.feature.generate-test-data.tasks]
generate-test-data = "python generate-test-data.py"

[tool.pixi.environments]
generate-test-data = {features = ["generate-test-data"], solve-group = "default"}
